name: "Check and Publish Docs"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.md'
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # install sphinx related package and build sphinx files
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "pip install sphinx-markdown-tables nbsphinx jinja2 recommonmark sphinx_rtd_theme"


    # add .nojekyll to notice Pages use the _* dirs
    - name: copy the generated site
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        mkdir public
        touch public/.nojekyll
        cp -r docs/_build/html/* public/

    # push to gh-pages branch
    - name: github pages deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: public
